on: [push]

jobs:
  runs-on: ubuntu-latest
  test:
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
    - name: test
      run: |
        npm ci
        npm test
      env:
        CI: true
  lint:
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
    - name: lint
      run: |
        npm ci
        npm run lint
      env:
        CI: true
