on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
    - name: test
      run: npm test
      env:
        CI: true
    - name: lint
      run: npm run lint
      env:
        CI: true
